//jquery-json
(function(e){e.toJSON=function(a){if(typeof JSON=="object"&&JSON.stringify)return JSON.stringify(a);var b=typeof a;if(a===null)return"null";if(b!="undefined"){if(b=="number"||b=="boolean")return a+"";if(b=="string")return e.quoteString(a);if(b=="object"){if(typeof a.toJSON=="function")return e.toJSON(a.toJSON());if(a.constructor===Date){var c=a.getUTCMonth()+1;if(c<10)c="0"+c;var d=a.getUTCDate();if(d<10)d="0"+d;b=a.getUTCFullYear();var f=a.getUTCHours();if(f<10)f="0"+f;var g=a.getUTCMinutes();if(g<
10)g="0"+g;var h=a.getUTCSeconds();if(h<10)h="0"+h;a=a.getUTCMilliseconds();if(a<100)a="0"+a;if(a<10)a="0"+a;return'"'+b+"-"+c+"-"+d+"T"+f+":"+g+":"+h+"."+a+'Z"'}if(a.constructor===Array){c=[];for(d=0;d<a.length;d++)c.push(e.toJSON(a[d])||"null");return"["+c.join(",")+"]"}c=[];for(d in a){b=typeof d;if(b=="number")b='"'+d+'"';else if(b=="string")b=e.quoteString(d);else continue;if(typeof a[d]!="function"){f=e.toJSON(a[d]);c.push(b+":"+f)}}return"{"+c.join(", ")+"}"}}};e.evalJSON=function(a){if(typeof JSON==
"object"&&JSON.parse)return JSON.parse(a);return eval("("+a+")")};e.secureEvalJSON=function(a){if(typeof JSON=="object"&&JSON.parse)return JSON.parse(a);var b=a;b=b.replace(/\\["\\\/bfnrtu]/g,"@");b=b.replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]");b=b.replace(/(?:^|:|,)(?:\s*\[)+/g,"");if(/^[\],:{}\s]*$/.test(b))return eval("("+a+")");else throw new SyntaxError("Error parsing JSON, source is not valid.");};e.quoteString=function(a){if(a.match(i))return'"'+a.replace(i,
function(b){var c=j[b];if(typeof c==="string")return c;c=b.charCodeAt();return"\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"';return'"'+a+'"'};var i=/["\\\x00-\x1f\x7f-\x9f]/g,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"}})(jQuery);

//jstorage
(function(g){function m(){if(e.jStorage)try{d=n(String(e.jStorage))}catch(a){e.jStorage="{}"}else e.jStorage="{}";j=e.jStorage?String(e.jStorage).length:0}function k(){try{e.jStorage=o(d);if(b){b.setAttribute("jStorage",e.jStorage);b.save("jStorage")}j=e.jStorage?String(e.jStorage).length:0}catch(a){}}function l(a){if(!a||typeof a!="string"&&typeof a!="number")throw new TypeError("Key name must be string or numeric");return true}if(!g||!(g.toJSON||Object.toJSON||window.JSON))throw Error("jQuery, MooTools or Prototype needs to be loaded before jStorage!");
var d={},e={jStorage:"{}"},b=null,j=0,o=g.toJSON||Object.toJSON||window.JSON&&(JSON.encode||JSON.stringify),n=g.evalJSON||window.JSON&&(JSON.decode||JSON.parse)||function(a){return String(a).evalJSON()},f=false;_XMLService={isXML:function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?a.nodeName!=="HTML":false},encode:function(a){if(!this.isXML(a))return false;try{return(new XMLSerializer).serializeToString(a)}catch(c){try{return a.xml}catch(h){}}return false},decode:function(a){var c="DOMParser"in
window&&(new DOMParser).parseFromString||window.ActiveXObject&&function(h){var i=new ActiveXObject("Microsoft.XMLDOM");i.async="false";i.loadXML(h);return i};if(!c)return false;a=c.call("DOMParser"in window&&new DOMParser||window,a,"text/xml");return this.isXML(a)?a:false}};g.jStorage={version:"0.1.5.0",set:function(a,c){l(a);if(_XMLService.isXML(c))c={_is_xml:true,xml:_XMLService.encode(c)};d[a]=c;k();return c},get:function(a,c){l(a);if(a in d)return typeof d[a]=="object"&&d[a]._is_xml&&d[a]._is_xml?
_XMLService.decode(d[a].xml):d[a];return typeof c=="undefined"?null:c},deleteKey:function(a){l(a);if(a in d){delete d[a];k();return true}return false},flush:function(){d={};k();try{window.localStorage.clear()}catch(a){}return true},storageObj:function(){function a(){}a.prototype=d;return new a},index:function(){var a=[],c;for(c in d)d.hasOwnProperty(c)&&a.push(c);return a},storageSize:function(){return j},currentBackend:function(){return f},storageAvailable:function(){return!!f},reInit:function(){var a;
if(b&&b.addBehavior){a=document.createElement("link");b.parentNode.replaceChild(a,b);b=a;b.style.behavior="url(#default#userData)";document.getElementsByTagName("head")[0].appendChild(b);b.load("jStorage");a="{}";try{a=b.getAttribute("jStorage")}catch(c){}e.jStorage=a;f="userDataBehavior"}m()}};(function(){if("localStorage"in window)try{if(window.localStorage){e=window.localStorage;f="localStorage"}}catch(a){}else if("globalStorage"in window)try{if(window.globalStorage){e=window.globalStorage[window.location.hostname];
f="globalStorage"}}catch(c){}else{b=document.createElement("link");if(b.addBehavior){b.style.behavior="url(#default#userData)";document.getElementsByTagName("head")[0].appendChild(b);b.load("jStorage");var h="{}";try{h=b.getAttribute("jStorage")}catch(i){}e.jStorage=h;f="userDataBehavior"}else{b=null;return}}m()})()})(window.jQuery||window.$);

jQuery(document).ready(function(){
  jQuery('#author').val(jQuery.jStorage.get('comment_author'));
  jQuery('#email').val(jQuery.jStorage.get('comment_author_email'));
  jQuery('#url').val(jQuery.jStorage.get('comment_author_url'));
  jQuery("#commentform").submit(function(){
    jQuery.jStorage.set('comment_author', jQuery('#author').val());
    jQuery.jStorage.set('comment_author_email', jQuery('#email').val());
    jQuery.jStorage.set('comment_author_url', jQuery('#url').val());
    return true;
  });
});